export const TAB = 9; // "\t"
export const LINEFEED = 10; // "\n"
export const SPACE = 32; // " "
export const QUOTE = 34; // "'"
export const APOSTROPHE = 39; // "'"
export const DASH = 45; // "-"
export const DOT = 46; // "."
export const SLASH = 47; // "/"
export const COLON = 58; // ":"
export const OPEN_ANGLE_BRACKET = 60; // "<"
export const EQUALS = 61; // "="
export const CLOSE_ANGLE_BRACKET = 62; // ">"
export const OPEN_BRACE = 123; // "{"
export const CLOSE_BRACE = 125; // "}"
