name: docs-deploy

on:
  push:
    branches:
      - master
    paths:
      - 'packages/site/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 5
      - uses: actions/cache@v2
        id: pnpm-store
        with:
          path: ~/.pnpm-store/v3
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - run: pnpm i --frozen-lockfile
      - run: pnpm run export
        working-directory: 'packages/site'
      - name: Publish
        uses: cloudflare/wrangler-action@1.1.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'packages/site'
