name: docs-deploy

on:
  push:
    branches:
      - master
    paths:
      - 'packages/site/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - run: npm i -g pnpm@6
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - run: pnpm i --frozen-lockfile
      - run: pnpm run export
        working-directory: 'packages/site'
      - name: Publish
        uses: cloudflare/wrangler-action@1.1.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'packages/site'
