name: mdsvex

on:
  push:
    branches:
      - main
      - next
    paths-ignore:
      - 'site/**'
  pull_request:
    branches:
      - main
      - next
    paths-ignore:
      - 'site/**'

jobs:
  e2e:
    name: e2e
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i -g pnpm@10.33.0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - run: pnpm i --frozen-lockfile
      - run: pnpm --filter=!site --filter=!incremental-parse-test --filter=!mdsvex-demo -r build
      - run: pnpm exec playwright install
      - run: pnpm test:e2e
