export const TAB = 9; // "\t"
export const LINEFEED = 10; // "\n"
export const SPACE = 32; // " "
export const QUOTE = 34; // "'"
export const OCTOTHERP = 35; // "#"
export const APOSTROPHE = 39; // "'"
export const DASH = 45; // "-"
export const DOT = 46; // "."
export const SLASH = 47; // "/"
export const COLON = 58; // ":"
export const OPEN_ANGLE_BRACKET = 60; // "<"
export const EQUALS = 61; // "="
export const CLOSE_ANGLE_BRACKET = 62; // ">"
export const AT = 64; // "@"
export const OPEN_BRACE = 123; // "{"
export const CLOSE_BRACE = 125; // "}"
export const UPPERCASE_A = 65; // "A"
export const UPPERCASE_Z = 90; // "Z"
export const BACKSLASH = 92; // "\"
export const BACKTICK = 96;
export const LOWERCASE_A = 97; // "A"
export const LOWERCASE_Z = 122; // "Z"
export const PIPE = 124; // "|"
export const RE_BLOCK_BRANCH = /^{\s*(?::|\/)/;
export const RE_SCRIPT_STYLE = /^<\/(?:script|style)\s*>/;
export const RE_COMMENT_START = /^<!--/;
export const RE_COMMENT_END = /^-->/;
export const RE_END_TAG_START = /^<\s*\//;
export const RE_ONLY_WHITESPACE = /^\s*$/;
